In [69]:
import numpy as np
import math
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import expm

In [70]:
#Definir os parametros
alphay = 1
alphaz = 1
j = 1
tau = 1

In [71]:
#Iniciar os operadores com zero
Jz = np.zeros((2*j + 1 , 2*j + 1))
Jy = np.zeros((2*j + 1 , 2*j + 1))
Jz2 = np.zeros((2*j + 1 , 2*j + 1))

In [72]:
#Definir Jz
m=-j
for i in range(0,2*j+1,1):
    Jz[i,i] = m
    m = m + 1
Jz

array([[-1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [73]:
#Definir Jz^2
Jz2 = Jz**2
Jz2

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [74]:
#Definir Jy

#Jy[0,0] = 0
#Jy[0,1] = 
m = -j
for i in range(0,2*j):
    if(i<2*j):
        Jy[i,i+1] = -math.sqrt((j*(j + 1) - m*(m + 1)))
        Jy[i,i-1] = math.sqrt((j*(j + 1) - m*(m - 1))) 
        Jy[i+1,i] = math.sqrt((j*(j + 1) - m*(m + 1)))
        Jy[i-1,i] = -math.sqrt((j*(j + 1) - m*(m - 1))) 
        m = m + 1
print(Jy)

[[ 0.         -1.41421356  0.        ]
 [ 1.41421356  0.         -1.41421356]
 [-0.          1.41421356  0.        ]]


In [79]:
#Definindo o operador F e atualizando as matrizes 
term1 = (-1)*complex(0,1)*((tau*Jz2)/(2*j + 1))
print(term1)

[[0.-0.33333333j 0.-0.j         0.-0.j        ]
 [0.-0.j         0.-0.j         0.-0.j        ]
 [0.-0.j         0.-0.j         0.-0.33333333j]]
